### ISSUE TITLE
Fails to call krafix-osx after update to 20.3.0

### ISSUE THREAD

**Issue by anissen** [Kode/vscode-kha#22]
After updating the Kha extension I get the following output trying to run a project from Visual Studio Code:
```
> Executing task: node /Users/nissen/.vscode/extensions/kodetech.kha-20.3.0/Kha/make.js debug-html5 --debug <

Using Kha (unversioned) from /Users/nissen/.vscode/extensions/kodetech.kha-20.3.0/Kha
Creating Kha project.
Exporting asset 1 of 2 (kenpixel_mini_square.ttf).
Exporting asset 2 of 2 (tile_crate.png).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/nissen/.vscode/extensions/kodetech.kha-20.3.0/Kha/Kinc/Tools/krafix/krafix-osx EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn /Users/nissen/.vscode/extensions/kodetech.kha-20.3.0/Kha/Kinc/Tools/krafix/krafix-osx',
  path: '/Users/nissen/.vscode/extensions/kodetech.kha-20.3.0/Kha/Kinc/Tools/krafix/krafix-osx',
  spawnargs: [
    'essl',
    '/Users/nissen/.vscode/extensions/kodetech.kha-20.3.0/Kha/Sources/Shaders/painter-colored.frag.glsl',
    '/Users/nissen/code/rogue-cosy/build/debug-html5-resources/painter-colored.frag.essl.temp',
    '/Users/nissen/code/rogue-cosy/build/temp',
    'debug-html5'
  ]
}
The terminal process terminated with exit code: 1
```

It appears to be a pretty general Node permissions issues. It worked fine in the last extension version so I believe it to be a regression.

**Comment by RobDangerous** [comment]
I can not reproduce that problem, can you try to re-install the extension?

**Comment by anissen** [comment]
Reinstalling the Kha and krafix extensions did actually fix this issue! Good call 👍 
Thanks!
